FROM golang:1.7-alpine

ADD . /home
        
WORKDIR /home

RUN \
       apk add --no-cache bash git openssh && \
       go get -u github.com/jeansferreira/teste_neoway 
       

CMD ["go","run","main.go"]
